apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-deleted
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.122.101
  share: /var/nfs/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4