apiVersion: batch/v1
kind: CronJob
metadata:
  name: codelabs-postgres-backup
spec:
  # Run the job every Monday, Wednesday, and Friday at midnight
  timeZone: America/Bogota
  schedule: "0 0 * * 1,3,5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: codelabs-postgres-backup
              image: pedrochaparroupb/postgres-rclone-backup-utility:0.0.1
              envFrom:
                - secretRef:
                    name: codelabs-postgres-backup-secret

              volumeMounts:
                # Mount backups volume to the container
                - name: codelabs-postgres-backup-volume
                  mountPath: /var/backups/db
                # Mount rclone configuration to the container
                - name: codelabs-postgres-backup-rclone-config
                  mountPath: /.config/rclone.conf

          # Don't restart the container, even if it fails
          restartPolicy: Never

          volumes:
            - name: codelabs-postgres-backup-volume
              persistentVolumeClaim:
                claimName: codelabs-postgres-backup-pvc

            - name: codelabs-postgres-backup-rclone-config
              # This requires the rclone.conf file to be present in all nodes
              hostPath:
                path: /etc/rclone/rclone.conf
                type: File
