apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codelabs-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: codelabs-web
    spec:
      containers:
        - name: codelabs-web
          image: ghcr.io/upb-code-labs/react-client:0.50.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "125m"
          ports:
            - name: http
              containerPort: 80
              # hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: codelabs-web
spec:
  type: ClusterIP # Only accessible from within the cluster
  selector:
    app: codelabs-web
  ports:
    - name: http
      port: 80
      targetPort: 80
