apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codelabs-static-files-pvc
spec:
  storageClassName: nfs-csi-retained
  resources:
    requests:
      storage: 150Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Multiple pods can access the volume
