apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codelabs-postgres-pvc
spec:
  storageClassName: nfs-csi-retained
  resources:
    requests:
      storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
