apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: codelabs-postgres
spec:
  selector:
    matchLabels:
      app: codelabs-postgres
  serviceName: codelabs-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: codelabs-postgres
    spec:
      containers:
        - name: codelabs-postgres
          image: docker.io/library/postgres:16.1-alpine3.19
          securityContext:
            runAsUser: 70
            runAsGroup: 70
            fsGroup: 70
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
            limits:
              memory: "1.0Gi"
              # cpu: "256m"
          ports:
            - name: pg
              containerPort: 5432
          # Just required the first time to initialize the database
          # envFrom:
            # - secretRef:
                # name: codelabs-postgres-secrets
          volumeMounts:
            - name: codelabs-postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: codelabs-postgres-volume
          persistentVolumeClaim:
            claimName: codelabs-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codelabs-postgres
spec:
  type: ClusterIP # Only accessible from within the cluster
  selector:
    app: codelabs-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432