apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs-submissions-status-updater-svc
spec:
  # Number of replicas to be used in production environment
  # replicas: 2
  # Number of replicas to be used in local environment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: codelabs-submissions-status-updater-svc
  template:
    metadata:
      labels:
        app: codelabs-submissions-status-updater-svc
    spec:
      containers:
        - name: codelabs-submissions-status-updater-svc
          image: ghcr.io/upb-code-labs/submissions-status-updater-microservice:0.2.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              # cpu: "125m"
          envFrom:
            - secretRef:
                name: submissions-status-updater-secrets