apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelabs-tests-runner-svc
spec:
  # Number of replicas to be used in production environment
  # replicas: 3
  # Number of replicas to be used in local environment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: codelabs-tests-runner-svc
  template:
    metadata:
      labels:
        app: codelabs-tests-runner-svc
    spec:
      containers:
        - name: codelabs-tests-runner-svc
          image: ghcr.io/upb-code-labs/tests-microservice:0.1.3
          # Resources for production environment
          resources:
            requests:
              memory: "1.0Gi"
              cpu: "250m"
            limits:
              memory: "2.0Gi"
              # cpu: "750m"
          # Resources for local environment
          # resources:
            # limits:
              # memory: "512Mi"
              # cpu: "1000m"
          env:
            - name: STATIC_FILES_MICROSERVICE_ADDRESS
              value: http://codelabs-static-files:8081
          envFrom:
            - secretRef:
                name: tests-runner-secrets